version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    # Check for updates every Monday
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps): "
      prefix-development: "chore(deps-dev): "
  - package-ecosystem: "cargo"
    directories:
      - "/"
      - "/crates/cli"
      - "/crates/macros"
      - "/tests"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps): "
      prefix-development: "chore(deps-dev): "
