[package]
name = "ext-php-rs-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.5"
dlopen = "0.1.8"
dlopen_derive = "0.1.4"
libloading = "0.7"

ext-php-rs = { path = "../../" }
ext-php-rs-describe = { path = "../describe" }