[target.'cfg(not(target_os = "windows"))']
rustflags = ["-C", "link-arg=-Wl,-undefined,dynamic_lookup"]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld"

[target.i686-pc-windows-msvc]
linker = "rust-lld"

[alias]
ci-test = "hack test --package ext-php-rs --package tests --feature-powerset --clean-per-run --exclude-features=link-php"
ci-test-link = "hack test --package ext-php-rs --feature-powerset --clean-per-run --features=link-php"
ci-test-other = "hack test --workspace --exclude ext-php-rs --exclude tests --feature-powerset"
